import { Button, VerticalBox, ComboBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> clicks: 0;
    in-out property<string> name: "";
    in-out property<[string]> names: [""];
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Clicks: \{root.clicks}";
        }
        Text {
            text: "\{root.name}";
        }
        Button {
            text: "Increase value";
            height: 30%;
            clicked => {
                root.request-increase-value();
            }
        }

    ComboBox {
        height: self.preferred-height;
                model: root.names;
        current-value: "first";
    }
    }
}
